# Generated by Django 4.0.4 on 2022-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='AudioParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('file', models.URLField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('chroma_stft', models.FloatField(blank=True, null=True)),
                ('spec_cent', models.FloatField(blank=True, null=True)),
                ('spec_bw', models.FloatField(blank=True, null=True)),
                ('rolloff', models.FloatField(blank=True, null=True)),
                ('zcr', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(blank=True, null=True)),
                ('prediction', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
