# Generated by Django 4.0.4 on 2022-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='wer_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
